#!/usr/bin/env bash
#
# install.sh - private-5g-router one-shot installer
# Run: sudo ./install.sh
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/scripts/_lib.sh"

require_root

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_prompt() {
    local var="$1" prompt="$2" default="$3"
    printf '%s [%s]: ' "${prompt}" "${default}"
    read -r _ans
    printf -v "${var}" '%s' "${_ans:-${default}}"
}

_prompt_silent() {
    local var="$1" prompt="$2" default="$3"
    printf '%s (press enter to use generated default): ' "${prompt}"
    read -rs _ans
    printf '\n'
    printf -v "${var}" '%s' "${_ans:-${default}}"
}

_STAGE=0
run_stage() {
    local label="$1"; shift
    _STAGE=$(( _STAGE + 1 ))
    printf '\n=== Stage %d: %s ===\n' "${_STAGE}" "${label}"
    if ! "$@"; then
        printf '\nFAIL: "%s" did not complete.\n' "${label}" >&2
        printf 'To undo all changes: sudo %s/scripts/rollback.sh\n' "${SCRIPT_DIR}" >&2
        exit 1
    fi
    printf 'PASS: %s\n' "${label}"
}

# ---------------------------------------------------------------------------
# Check for existing .env
# ---------------------------------------------------------------------------

_configure=true

if [[ -f "${P5R_ENV}" ]] \
    && grep -q '^WIFI_SSID=[^$]' "${P5R_ENV}" \
    && ! grep -qE '=PENDING' "${P5R_ENV}"; then
    printf '\n.env already exists with values.\n'
    _prompt _reuse "Proceed with existing .env? (Y to reuse, N to reconfigure)" "Y"
    [[ "${_reuse}" =~ ^[Yy] ]] && _configure=false
fi

# ---------------------------------------------------------------------------
# Detect modem
# ---------------------------------------------------------------------------

printf '\n=== Detecting modem ===\n'
DETECT_OUT="$("${SCRIPT_DIR}/scripts/detect_modem.sh" 2>&1 || true)"
printf '%s\n' "${DETECT_OUT}"

MODE="$(printf '%s\n' "${DETECT_OUT}" | grep '^MODE=' | cut -d= -f2)"

case "${MODE}" in
    network)
        DETECTED_WAN_IF="$(printf '%s\n' "${DETECT_OUT}" \
            | grep 'Likely WAN_IF values to try:' \
            | sed 's/.*to try: //' | awk '{print $1}')"
        DETECTED_WAN_IF="${DETECTED_WAN_IF:-eth1}"
        ;;
    ppp)
        DETECTED_WAN_IF="ppp0"
        DETECTED_PPP_DEV="$(printf '%s\n' "${DETECT_OUT}" \
            | grep -oE '/dev/ttyUSB[0-9]+' | head -1 || true)"
        DETECTED_PPP_DEV="${DETECTED_PPP_DEV:-/dev/ttyUSB2}"
        ;;
    storage)
        die "Modem is in storage/CD-ROM mode. Install usb-modeswitch, replug the dongle, and re-run."
        ;;
    *)
        die "Modem not detected. Check dmesg and lsusb -t, then re-run."
        ;;
esac

log "Mode: ${MODE}"

# ---------------------------------------------------------------------------
# Interactive configuration
# ---------------------------------------------------------------------------

if [[ "${_configure}" == true ]]; then
    _GEN_SSID="p5n-$(tr -dc 'A-Z0-9' < /dev/urandom | head -c 6)"
    _GEN_PIN="$(tr -dc '0-9' < /dev/urandom | head -c 12)"

    printf '\n=== Configuration ===\n\n'

    _prompt      WIFI_SSID       "WiFi SSID"            "${_GEN_SSID}"
    _prompt_silent WIFI_PASSPHRASE "WiFi passphrase (8-63 chars)" "${_GEN_PIN}"

    while [[ ${#WIFI_PASSPHRASE} -lt 8 || ${#WIFI_PASSPHRASE} -gt 63 ]]; do
        printf 'Passphrase must be 8-63 characters.\n'
        _prompt_silent WIFI_PASSPHRASE "WiFi passphrase" "${_GEN_PIN}"
    done

    _prompt WIFI_COUNTRY  "WiFi country code (ISO 3166-1)" "GB"
    _prompt WAN_IF        "WAN interface"                  "${DETECTED_WAN_IF}"

    printf '\n--- Config portal credentials ---\n'
    printf '  The portal at http://<gateway>/ is protected by HTTP Basic Auth.\n'
    printf '  Default: admin / p5g123  -- change these.\n\n'
    _prompt        PORTAL_USER "Portal username" "admin"
    _prompt_silent PORTAL_PASS "Portal password" "p5g123"
    while [[ ${#PORTAL_PASS} -lt 6 ]]; do
        printf 'Password must be at least 6 characters.\n'
        _prompt_silent PORTAL_PASS "Portal password" "p5g123"
    done

    APN="" PPP_DEV="" PPP_USER="" PPP_PASS=""
    if [[ "${MODE}" == "ppp" ]]; then
        printf 'APN (ask your carrier, e.g. "internet"): '
        read -r APN
        [[ -n "${APN}" ]] || die "APN is required for PPP mode."
        _prompt PPP_DEV "PPP serial device" "${DETECTED_PPP_DEV}"
        _prompt PPP_USER "PPP username (leave blank if not required)" ""
        if [[ -n "${PPP_USER}" ]]; then
            _prompt_silent PPP_PASS "PPP password" ""
        fi
    fi

    # --- Write .env ---
    log "Writing ${P5R_ENV}"
    cat >"${P5R_ENV}" <<EOF
# private-5g-router .env
# Generated by install.sh on $(date)

# --- Interfaces ---
MGMT_IF=eth0
LAN_IF=wlan0
WAN_IF=${WAN_IF}

# --- WiFi AP ---
WIFI_SSID=${WIFI_SSID}
WIFI_PASSPHRASE=${WIFI_PASSPHRASE}
WIFI_COUNTRY=${WIFI_COUNTRY}
WIFI_CHANNEL=6

# --- LAN subnet ---
LAN_GATEWAY=10.77.0.1
LAN_SUBNET=10.77.0.0/24
LAN_SUBNET_MASK=255.255.255.0
DHCP_RANGE_START=10.77.0.50
DHCP_RANGE_END=10.77.0.200
DHCP_LEASE=12h

# --- Watchdog ---
HEALTHCHECK_TARGET=1.1.1.1
HEALTHCHECK_FAILURES=3
HEALTHCHECK_INTERVAL=60

# --- Config portal ---
PORTAL_USER=${PORTAL_USER}
PORTAL_PASS=${PORTAL_PASS}
EOF

    if [[ "${MODE}" == "ppp" ]]; then
        {
            printf 'APN=%s\n' "${APN}"
            printf 'PPP_DEV=%s\n' "${PPP_DEV}"
            [[ -n "${PPP_USER}" ]] && printf 'PPP_USER=%s\nPPP_PASS=%s\n' "${PPP_USER}" "${PPP_PASS}"
        } >>"${P5R_ENV}"
    fi

    chmod 0600 "${P5R_ENV}"
    log ".env written"
fi

# Load .env so we can use values in the summary at the end.
load_env

# ---------------------------------------------------------------------------
# Run stages
# ---------------------------------------------------------------------------

printf '\n=== Running setup stages ===\n'

run_stage "Prerequisites"      "${SCRIPT_DIR}/scripts/setup_prereqs.sh"

if [[ "${MODE}" == "network" ]]; then
    run_stage "WAN - network mode" "${SCRIPT_DIR}/scripts/setup_network_mode.sh"
else
    run_stage "WAN - PPP mode"     "${SCRIPT_DIR}/scripts/setup_ppp_mode.sh"
fi

run_stage "WiFi access point"  "${SCRIPT_DIR}/scripts/setup_ap_mode.sh"
run_stage "DHCP and DNS"       "${SCRIPT_DIR}/scripts/setup_dhcp.sh"
run_stage "NAT and firewall"   "${SCRIPT_DIR}/scripts/setup_nat.sh"
run_stage "Boot services"      "${SCRIPT_DIR}/scripts/install_services.sh" "${MODE}"

# ---------------------------------------------------------------------------
# End-to-end healthcheck
# ---------------------------------------------------------------------------

printf '\n=== Healthcheck ===\n'
_HC="PASS"
"${SCRIPT_DIR}/scripts/healthcheck_modem.sh" || _HC="FAIL"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

_GW="${LAN_GATEWAY:-10.77.0.1}"

printf '\n'
printf '============================================\n'
printf '  Installation complete\n'
printf '============================================\n'
printf '  SSID        : %s\n' "${WIFI_SSID}"
printf '  Passphrase  : see .env (chmod 0600)\n'
printf '  Gateway IP  : %s\n' "${_GW}"
printf '  Healthcheck : %s\n' "${_HC}"
printf '  Portal      : http://%s/  (user: %s)\n' "${_GW}" "${PORTAL_USER:-admin}"
printf '\n'
printf '  Connect to "%s" and browse.\n' "${WIFI_SSID}"
printf '  Diagnostics : sudo %s/scripts/healthcheck_modem.sh\n' "${SCRIPT_DIR}"
printf '  Rollback    : sudo %s/scripts/rollback.sh\n' "${SCRIPT_DIR}"
printf '============================================\n'
